/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketCodeRouteImport } from './routes/ticket.$code'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyBookingsRouteImport } from './routes/_authenticated/my-bookings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin-users'
import { Route as AuthenticatedAdminTripsRouteImport } from './routes/_authenticated/admin-trips'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin-packages'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin-homepage'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin-gallery'
import { Route as AuthenticatedAdminBusesRouteImport } from './routes/_authenticated/admin-buses'
import { Route as AuthenticatedAdminBusLayoutsRouteImport } from './routes/_authenticated/admin-bus-layouts'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin-bookings'
import { Route as AuthenticatedAdminAssetsRouteImport } from './routes/_authenticated/admin-assets'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCodeRoute = TicketCodeRouteImport.update({
  id: '/ticket/$code',
  path: '/ticket/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyBookingsRoute = AuthenticatedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTripsRoute = AuthenticatedAdminTripsRouteImport.update({
  id: '/admin-trips',
  path: '/admin-trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/admin-packages',
    path: '/admin-packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/admin-homepage',
    path: '/admin-homepage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/admin-gallery',
    path: '/admin-gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBusesRoute = AuthenticatedAdminBusesRouteImport.update({
  id: '/admin-buses',
  path: '/admin-buses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBusLayoutsRoute =
  AuthenticatedAdminBusLayoutsRouteImport.update({
    id: '/admin-bus-layouts',
    path: '/admin-bus-layouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/admin-bookings',
    path: '/admin-bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAssetsRoute =
  AuthenticatedAdminAssetsRouteImport.update({
    id: '/admin-assets',
    path: '/admin-assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/admin-assets': typeof AuthenticatedAdminAssetsRoute
  '/admin-bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin-bus-layouts': typeof AuthenticatedAdminBusLayoutsRoute
  '/admin-buses': typeof AuthenticatedAdminBusesRoute
  '/admin-gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin-homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin-packages': typeof AuthenticatedAdminPackagesRoute
  '/admin-trips': typeof AuthenticatedAdminTripsRoute
  '/admin-users': typeof AuthenticatedAdminUsersRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/admin-assets': typeof AuthenticatedAdminAssetsRoute
  '/admin-bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin-bus-layouts': typeof AuthenticatedAdminBusLayoutsRoute
  '/admin-buses': typeof AuthenticatedAdminBusesRoute
  '/admin-gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin-homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin-packages': typeof AuthenticatedAdminPackagesRoute
  '/admin-trips': typeof AuthenticatedAdminTripsRoute
  '/admin-users': typeof AuthenticatedAdminUsersRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/draw': typeof DrawRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/_authenticated/admin-assets': typeof AuthenticatedAdminAssetsRoute
  '/_authenticated/admin-bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin-bus-layouts': typeof AuthenticatedAdminBusLayoutsRoute
  '/_authenticated/admin-buses': typeof AuthenticatedAdminBusesRoute
  '/_authenticated/admin-gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin-homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin-packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin-trips': typeof AuthenticatedAdminTripsRoute
  '/_authenticated/admin-users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/ticket/$code': typeof TicketCodeRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/draw'
    | '/gallery'
    | '/packages'
    | '/admin-assets'
    | '/admin-bookings'
    | '/admin-bus-layouts'
    | '/admin-buses'
    | '/admin-gallery'
    | '/admin-homepage'
    | '/admin-packages'
    | '/admin-trips'
    | '/admin-users'
    | '/audit'
    | '/dashboard'
    | '/my-bookings'
    | '/profile'
    | '/ticket/$code'
    | '/api/public/bootstrap-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/draw'
    | '/gallery'
    | '/packages'
    | '/admin-assets'
    | '/admin-bookings'
    | '/admin-bus-layouts'
    | '/admin-buses'
    | '/admin-gallery'
    | '/admin-homepage'
    | '/admin-packages'
    | '/admin-trips'
    | '/admin-users'
    | '/audit'
    | '/dashboard'
    | '/my-bookings'
    | '/profile'
    | '/ticket/$code'
    | '/api/public/bootstrap-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/draw'
    | '/gallery'
    | '/packages'
    | '/_authenticated/admin-assets'
    | '/_authenticated/admin-bookings'
    | '/_authenticated/admin-bus-layouts'
    | '/_authenticated/admin-buses'
    | '/_authenticated/admin-gallery'
    | '/_authenticated/admin-homepage'
    | '/_authenticated/admin-packages'
    | '/_authenticated/admin-trips'
    | '/_authenticated/admin-users'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-bookings'
    | '/_authenticated/profile'
    | '/ticket/$code'
    | '/api/public/bootstrap-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  DrawRoute: typeof DrawRoute
  GalleryRoute: typeof GalleryRoute
  PackagesRoute: typeof PackagesRoute
  TicketCodeRoute: typeof TicketCodeRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$code': {
      id: '/ticket/$code'
      path: '/ticket/$code'
      fullPath: '/ticket/$code'
      preLoaderRoute: typeof TicketCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-bookings': {
      id: '/_authenticated/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof AuthenticatedMyBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-users': {
      id: '/_authenticated/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-trips': {
      id: '/_authenticated/admin-trips'
      path: '/admin-trips'
      fullPath: '/admin-trips'
      preLoaderRoute: typeof AuthenticatedAdminTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-packages': {
      id: '/_authenticated/admin-packages'
      path: '/admin-packages'
      fullPath: '/admin-packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-homepage': {
      id: '/_authenticated/admin-homepage'
      path: '/admin-homepage'
      fullPath: '/admin-homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-gallery': {
      id: '/_authenticated/admin-gallery'
      path: '/admin-gallery'
      fullPath: '/admin-gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-buses': {
      id: '/_authenticated/admin-buses'
      path: '/admin-buses'
      fullPath: '/admin-buses'
      preLoaderRoute: typeof AuthenticatedAdminBusesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-bus-layouts': {
      id: '/_authenticated/admin-bus-layouts'
      path: '/admin-bus-layouts'
      fullPath: '/admin-bus-layouts'
      preLoaderRoute: typeof AuthenticatedAdminBusLayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-bookings': {
      id: '/_authenticated/admin-bookings'
      path: '/admin-bookings'
      fullPath: '/admin-bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-assets': {
      id: '/_authenticated/admin-assets'
      path: '/admin-assets'
      fullPath: '/admin-assets'
      preLoaderRoute: typeof AuthenticatedAdminAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAssetsRoute: typeof AuthenticatedAdminAssetsRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminBusLayoutsRoute: typeof AuthenticatedAdminBusLayoutsRoute
  AuthenticatedAdminBusesRoute: typeof AuthenticatedAdminBusesRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminTripsRoute: typeof AuthenticatedAdminTripsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyBookingsRoute: typeof AuthenticatedMyBookingsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAssetsRoute: AuthenticatedAdminAssetsRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminBusLayoutsRoute: AuthenticatedAdminBusLayoutsRoute,
  AuthenticatedAdminBusesRoute: AuthenticatedAdminBusesRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
  AuthenticatedAdminTripsRoute: AuthenticatedAdminTripsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyBookingsRoute: AuthenticatedMyBookingsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  DrawRoute: DrawRoute,
  GalleryRoute: GalleryRoute,
  PackagesRoute: PackagesRoute,
  TicketCodeRoute: TicketCodeRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
